changelog:
  categories:
    - title: Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - maintenance
          - no-release-note
    - title: Maintenance
      labels:
        - maintenance
    - title: Dependencies
      labels:
        - dependencies
